In [4]:
import numpy as np
import pandas as pd 
df = pd.read_csv('C:\\Users\\deepak\\Summer Intership and Training\\Machine_Learning\\Assignment_2\\covid_toy.csv')

In [5]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [6]:
df = df.dropna()
df

age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[90 rows x 6 columns]

In [7]:
df = df.drop(columns=['age', 'fever'])

In [8]:
df.head()

gender cough     city has_covid
0    Male  Mild  Kolkata        No
1    Male  Mild    Delhi       Yes
2    Male  Mild    Delhi        No
3  Female  Mild  Kolkata        No
4  Female  Mild   Mumbai        No

In [9]:
from sklearn.preprocessing import OneHotEncoder

In [10]:
df.shape

(90, 4)

## Get_Dummies method

In [17]:
p = pd.get_dummies(df, columns=['gender','cough', 'city','has_covid'], drop_first= True)

In [18]:
p.shape

(90, 6)

In [19]:
ohe= OneHotEncoder(drop ='first', sparse = False , dtype = np.int32)

In [20]:
df_new = ohe.fit_transform(df[['gender', 'cough', 'city','has_covid']])

In [21]:
df_new.shape

(90, 6)

In [22]:
ohe= OneHotEncoder(drop ='first', sparse = False , dtype = np.int32)

In [23]:
df_new = ohe.fit_transform(df[['gender', 'cough', 'city','has_covid']])

In [24]:
df_new.shape

(90, 6)

## Column Transformer

In [6]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

from sklearn.preprocessing import OrdinalEncoder

In [7]:
df = pd.read_csv('C:\\Users\\deepak\\Summer Intership and Training\\Machine_Learning\\Assignment_2\\covid_toy.csv')

In [8]:
df

age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [9]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
x_train , x_test, y_train, y_test = train_test_split(df.drop(columns=['has_covid']), df['has_covid'], test_size=0.2)

In [11]:
x_test

age  gender  fever   cough       city
41   82    Male    NaN    Mild    Kolkata
60   24  Female  102.0  Strong  Bangalore
37   55    Male  100.0    Mild    Kolkata
89   46    Male  103.0  Strong  Bangalore
0    60    Male  103.0    Mild    Kolkata
34   74    Male  102.0    Mild     Mumbai
86   25    Male  104.0    Mild  Bangalore
75    5    Male  102.0    Mild    Kolkata
8    19  Female  100.0  Strong  Bangalore
4    65  Female  101.0    Mild     Mumbai
14   51    Male  104.0    Mild  Bangalore
23   80  Female   98.0    Mild      Delhi
84   69  Female   98.0  Strong     Mumbai
72   83  Female  101.0    Mild    Kolkata
1    27    Male  100.0    Mild      Delhi
52   47  Female  100.0  Strong  Bangalore
79   48  Female  103.0    Mild    Kolkata
61   81  Female   98.0  Strong     Mumbai
21   73    Male   98.0    Mild  Bangalore
68   54  Female  104.0  Strong    Kolkata

## Manually type output

In [12]:
# adding simple imputer to fever column
si = SimpleImputer()
x_train_fever = si.fit_transform(x_train[['fever']])
# also the test data
x_test_fever = si.fit_transform(x_test [['fever']])
x_train_fever.shape

(80, 1)

In [13]:
# Ordinal Encoding --> Cough
oe = OrdinalEncoder (categories = [['Mild', 'Strong']])
x_train_cough = oe.fit_transform(x_train [['cough']])

# also the test data
x_test_cough = oe.fit_transform(x_test[['cough']])

x_test_cough.shape

(20, 1)

In [14]:
#OneHotEncoding --> Gender city
ohe = OneHotEncoder(drop = 'first', sparse = False )
x_train_gender_city = ohe.fit_transform(x_train [['gender', 'city']])

# also the test data
x_test_gender_city = ohe.fit_transform(x_test[['gender', 'city']])

x_train_gender_city.shape

(80, 4)

In [17]:
# Extracting Age
x_train_age = x_train.drop(columns = ['gender', 'fever', 'cough', 'city']).values
#also the test data
x_test_age = x_test.drop(columns = ['gender', 'fever', 'cough', 'city']).values
x_train_age.shape

(80, 1)

In [21]:
x_train_transformed = np.concatenate((x_train_age, x_train_fever, x_train_gender_city, x_train_cough), axis = 1)

In [22]:
x_train_transformed.shape

(80, 7)

## By the help of column Transformer

In [24]:
from sklearn.compose import ColumnTransformer # This is how to import CoumnTransformer
transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(),['fever']), #in a 'fever' column by the help of si we fill missing value
    ('tnf2', OrdinalEncoder(categories=[['Mild','Strong']]), ['cough']),#by this process we encode
    ('tnf3', OneHotEncoder(sparse = False, drop='first'), ['gender', 'city'])
], remainder='passthrough')#rest value remains same

In [25]:
transformer.fit_transform(x_train).shape

(80, 7)

In [28]:
transformer.fit_transform(x_test).shape

(20, 7)

## what is function transformer in machine learning ?
The Function Transformer is a tool in scikit-learn, a popular Python library for machine learning, that allows you to apply a specified function to the input data. The Function Transformer can be useful for performing custom transformations of input data in a machine learning pipeline.
The Function Transformer takes as input a single function that will be applied to each sample in the data. This function can be any Python function that takes a single argument, such as a lambda function or a user-defined function. The function should return the transformed sample.

In [33]:
from sklearn.preprocessing import FunctionTransformer 
import numpy as np

# create a dataset 
X = np.array([[1, 2], [3, 4]])
# define the transformation function
log_transform = FunctionTransformer(np.log1p)
# apply the transformation to the dataset 
X_transformed = log_transform.transform(X)
# view the transformed data 
print(X_transformed)

[[0.69314718 1.09861229]
 [1.38629436 1.60943791]]


## Example 2

In [36]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np
X = np.array([[1, 2], [3, 4]])
def my_feature_engineering(X):
    return np.hstack((X,X**2))
custom_transformer = FunctionTransformer(my_feature_engineering)
X_transformed = custom_transformer.transform(X)
print(X_transformed)

[[ 1  2  1  4]
 [ 3  4  9 16]]


## Example 3

In [38]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

X = np.array([[1, 2], [3, 4]])

def my_feature_engineering(X):
    return np.hstack((X, X / np.max(X, axis=0)))

custom_transformer = FunctionTransformer(my_feature_engineering)
X_transformed = custom_transformer.transform(X)
print(X_transformed)


[[1.         2.         0.33333333 0.5       ]
 [3.         4.         1.         1.        ]]


## example 4

In [42]:
#3. Data Cleaning
from sklearn.preprocessing import FunctionTransformer 
import numpy as np
# create a dataset with missing values 
X = np.array([[1, 2], [3, np.nan]])
# define a custom cleaning function
def my_cleaning(X):
    X[np.isnan(X)] = 0
    return X
# create a Function Transformer to apply the custom function 
custom_transformer = FunctionTransformer(my_cleaning)
# apply the transformer to the input data
X_transformed = custom_transformer.transform(X)
print(X_transformed)

[[1. 2.]
 [3. 0.]]
