In [33]:
import numpy as np
import pandas as pd

In [34]:
df=pd.read_csv("C:\\Users\\deepak\\Summer Intership and Training\\Machine_Learning\\csv\\Social_Network_Ads.csv", usecols=['Age','EstimatedSalary','Purchased']
              )

In [35]:
df.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [36]:
x=df.drop(columns=['Purchased']) # independet column
y=df['Purchased']  # dependent column

In [37]:
from sklearn.model_selection import train_test_split

In [38]:
x_train, x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=23)

In [39]:
from sklearn.preprocessing import StandardScaler

In [40]:
sc=StandardScaler()

In [41]:
x_train_new=sc.fit_transform(x_train)

In [42]:
x_test_new=sc.transform(x_test)

In [43]:
# from sklearn naive_bayes import Burnollinb
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
classifier=GaussianNB()

In [47]:
classifier.fit(x_train_new,y_train)

GaussianNB()

In [48]:
y_pred=classifier.predict(x_test_new)

In [49]:
y_pred

array([0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0], dtype=int64)

In [50]:
from sklearn.metrics import confusion_matrix

In [51]:
cn = confusion_matrix(y_test, y_pred)

In [52]:
cn

array([[48,  2],
       [ 5, 25]], dtype=int64)

[[tp,fn]

[fp,tn]]

# applying rainforest

In [69]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.875

In [70]:
from sklearn.metrics import r2_score 
r2_score(y_test , y_pred)

0.4666666666666667

In [71]:
from sklearn.ensemble import RandomForestClassifier 

In [72]:
rf = RandomForestClassifier() 

In [73]:
rf.fit(x_train , y_train) 

RandomForestClassifier()

In [74]:
y_pred = rf.predict(x_test)

In [75]:
y_pred

array([0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0], dtype=int64)

In [76]:
r2_score(y_test , y_pred)

0.52